import React from "react";

import { Layout, Carousel } from "antd";
import NavBar from "../../../../components/NavBar";
import "./index.css";
const { Footer, Content } = Layout;

export default class HomeContent extends React.Component {
    render() {
        return (
            <Layout style={{ marginLeft: 200 }}>
                <NavBar />

                <Content style={{ margin: "24px 16px 0", overflow: "initial" }}>
                    <div style={{ padding: 24, background: "#fff", textAlign: "center" }}>
                        <Carousel autoplay style={{ width: 500, height: 100 }}>
                            <div>
                                <h3>1</h3>
                            </div>
                            <div>
                                <h3>2</h3>
                            </div>
                            <div>
                                <h3>3</h3>
                            </div>
                            <div>
                                <h3>4</h3>
                            </div>
                        </Carousel>
                        ...
                        <br />
                        Really
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        long
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        ...
                        <br />
                        content
                    </div>
                </Content>
                <Footer style={{ textAlign: "center" }}>
                    Copyright © 2012-2018 某某博客 版权所有 琼ICP备xxxxxxxx号
                </Footer>
            </Layout>
        );
    }
}
